name: cacco
version: '0.1.0.0'
category: Language
author: Kazuhiro Mizushima
maintainer: voqn.tyrant@gmail.com
copyright: 2017 Kazuhiro Mizushima
license: BSD3
github: VoQn/cacco
extra-source-files:
    - README.asciidoc
dependencies:
    - base >=4.7 && <5
    - text >=1.2 && <2
    - prettyprinter >=1.1 && <2.0
    - half >=0.2 && <1
    - scientific >=0.3 && <0.4
    - megaparsec >=7 && <8
    - lens >=4.15 && <5
    - recursion-schemes >=5.0 && <6
library:
    source-dirs: src
    ghc-options:
        - -Wall
        - -Wcompat
        - -optP-Wno-nonportable-include-path
    dependencies:
        - vector
        - deepseq >=1.4 && <2
        - mtl >=2.2 && <3
        - containers >=0.5 && <1
        - haskeline >=0.7 && <0.8
executables:
    cacco:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -optP-Wno-nonportable-include-path
        dependencies:
            - base
            - cacco
tests:
    test:
        main: Tasty.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -optP-Wno-nonportable-include-path
        dependencies:
            - tasty >=1.0 && <2.0
            - tasty-discover >=4.0 && <5.0
            - tasty-hspec >=1.1 && <2
            - tasty-quickcheck
            - tasty-smallcheck
            - smallcheck >=1.1 && <2.0
            - QuickCheck >=2.10 && <3.0
            - cacco
